defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.0

whitelist: &whitelist
  paths:
    - dist/*
    - node_modules/*
    
version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint TypeScript code
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test TypeScript code
          command: yarn test
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build TypeScript code
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: 
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: 
          name: Release
          command: yarn semantic-release

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          filters:
            branches:
              ignore:
                - master
          requires:
            - checkout
      - lint:
          filters:
            branches:
              ignore:
                - master
          requires:
            - checkout
      - build:
          filters:
            branches:
              ignore:
                - master
          requires:
            - test
            - lint

  release:
    jobs:
      - checkout:
          filters:
            branches:
              only: 
                - master
      - test:
          filters:
            branches:
              only: 
                - master
          requires:
            - checkout
      - lint:
          filters:
            branches:
              only: 
                - master
          requires:
            - checkout
      - build:
          filters:
            branches:
              only: 
                - master
          requires:
            - test
            - lint
      - deploy:
          filters:
            branches:
              only: 
                - master
          requires:
            - build